### PR TITLE
Updated windows rufus to recommend DD instead of ISO

### PR DESCRIPTION
**Pull request by commonsourcecs**
2 instances of text and 2 images changed

### CODE REVIEW

**Comment by philmmanjaro** [comment]
@Pattedetable: what do you think

**Comment by Pattedetable** [comment]
Both methods work for me.  Is there any advantage to using "DD Image" instead of "ISO Image"?  Since Manjaro is distributed as an ISO file, a few more steps are required for the "DD Image" option.  You first have to select the ISO file and then change to "DD Image".  The order is important.  The app won't let you pick an ISO file if you selected "DD Image".

Also, are those really genuine screenshots, or have the previous ones been modified in an image editor?  The font for "DD Image" does not match the one in the rest of the app (see for instance the "I" and "g" of "Image") and some options become greyed out in the app when selecting "DD Image", which is not visible in your pictures.

If there is an advantage to using "DD Image", I don't mind changing it, but I would also explain the steps necessary (the order of the steps), as well as provide actual screenshots.

**Comment by Pattedetable** [comment]
This is what I see in the app when selecting "DD Image" (after choosing the ISO file):
rufus

**Comment by commonsourcecs** [comment]
They were simply edited for speeds sake. (and I have no win install)
There have been multiple recent instances of new users following these instructions and running into problems with ISO method.
For example here: https://forum.manjaro.org/t/broke-my-system-an-hour-after-installation/32694/54

**Comment by Pattedetable** [comment]
Ok, sorry about that.  Major blunder on my part.  It worked fine on the systems I have access to so I kept it as is.  Merging, then will update screenshots.

**Pull request merged**
